// inkk companion — build step (`npm run build`). Three outputs:
//
//   lib/config.cjs       INKK_API_BASE (+ Supabase URL/key) from companion/.env.local,
//                        so the main process knows where /api/certify lives.
//   lib/scoring.cjs      esbuild CJS bundle of src/telemetry/{features,score}.js
//                        (entry lib/scoring-entry.js) — the main process scores with
//                        the SAME code the website and api/certify.mjs use.
//   renderer/bundle.js   esbuild IIFE bundle of renderer/app.js, with __SUPA_URL__,
//                        __SUPA_KEY__ and __API_BASE__ inlined (the renderer imports
//                        @supabase/supabase-js and ../../src/verify/code.js).
//
// The two generated .cjs files and bundle.js are gitignored; the app cannot
// run without them, which is why every script that launches or packages the
// app goes through this file first.

"use strict";

const esbuild = require("esbuild");
const fs = require("node:fs");
const path = require("node:path");

const HERE = __dirname;

// Load companion/.env.local (gitignored) into process.env so keys are set once
// in a file, not re-pasted into the shell each run. Simple KEY=VALUE parser;
// values already in the environment win.
function loadEnvLocal() {
  const p = path.join(HERE, ".env.local");
  if (!fs.existsSync(p)) return;
  for (const line of fs.readFileSync(p, "utf8").split("\n")) {
    const s = line.trim();
    if (!s || s.startsWith("#")) continue;
    const i = s.indexOf("=");
    if (i === -1) continue;
    const k = s.slice(0, i).trim();
    const v = s.slice(i + 1).trim().replace(/^["']|["']$/g, "");
    if (!(k in process.env)) process.env[k] = v;
  }
}

function readConfig() {
  return {
    INKK_API_BASE: process.env.INKK_API_BASE || "https://inkk.site",
    REACT_APP_SUPABASE_URL: process.env.REACT_APP_SUPABASE_URL || process.env.SUPABASE_URL || "",
    REACT_APP_SUPABASE_ANON_KEY: process.env.REACT_APP_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "",
  };
}

function writeConfig(cfg) {
  const out = path.join(HERE, "lib", "config.cjs");
  const body = "// Generated by build.js from companion/.env.local — do not edit, do not commit.\n"
    + `module.exports = ${JSON.stringify(cfg, null, 2)};\n`;
  fs.writeFileSync(out, body);
  console.log(`[build] lib/config.cjs (api base ${cfg.INKK_API_BASE})`);
}

async function bundleScoring() {
  await esbuild.build({
    entryPoints: [path.join(HERE, "lib", "scoring-entry.js")],
    bundle: true,
    format: "cjs",
    platform: "node",
    target: "node22",
    outfile: path.join(HERE, "lib", "scoring.cjs"),
    logLevel: "warning",
  });
  console.log("[build] lib/scoring.cjs");
}

async function bundleRenderer(cfg) {
  const entry = path.join(HERE, "renderer", "app.js");
  if (!fs.existsSync(entry)) {
    console.warn("[build] renderer/app.js not found — skipping the renderer bundle");
    return;
  }
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "chrome130",
    outfile: path.join(HERE, "renderer", "bundle.js"),
    // The renderer reads TOS_VERSION from src/components/Legal.js, a React
    // file; the JSX loader lets esbuild parse it (the component itself is
    // tree-shaken away).
    loader: { ".js": "jsx" },
    define: {
      __SUPA_URL__: JSON.stringify(cfg.REACT_APP_SUPABASE_URL),
      __SUPA_KEY__: JSON.stringify(cfg.REACT_APP_SUPABASE_ANON_KEY),
      __API_BASE__: JSON.stringify(cfg.INKK_API_BASE),
    },
    logLevel: "warning",
  });
  console.log("[build] renderer/bundle.js");
}

(async () => {
  loadEnvLocal();
  const cfg = readConfig();
  writeConfig(cfg);
  await bundleScoring();
  await bundleRenderer(cfg);
  if (!cfg.REACT_APP_SUPABASE_URL || !cfg.REACT_APP_SUPABASE_ANON_KEY) {
    console.warn("[build] No Supabase config in .env.local — certification will offer sign-in but cannot complete it. See companion/README.md.");
  }
})().catch((e) => { console.error("[build] failed:", e.message || e); process.exit(1); });
